### PR TITLE
apischema v0.16.5

### PR DESCRIPTION
**Pull request by wyfo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wyfo** [comment]
@conda-forge-admin, please rerender

**Comment by klauer** [comment]
The bot won’t automatically update the hash, so it’s something we have to do manually. You could update it here or we could just merge #15 - either way is fine to me.

For the previous PR, a re-render shouldn’t be necessary after just a version pin change. It’s generally good practice to rerender when unsure, but failing that the next micro release would pick it up regardless.

(By the way, I’ll be a bit slow to respond for the next couple weeks.)

**Comment by wyfo** [comment]
> The bot won’t automatically update the hash, so it’s something we have to do manually. You could update it here or we could just merge #16 - either way is fine to me.

Was the creation of #16 automatic or did you trigger it yourself?

> (By the way, I’ll be a bit slow to respond for the next couple weeks.)

Merry Christmas! 😃

**Comment by klauer** [comment]
It was automatic. And same to you, @wyfo! 😄

**Pull request closed without merging**
